fetch("https://www.youtube.com/youtubei/v1/live_chat/send_message?key=AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8&prettyPrint=false", {
  "headers": {
    "accept": "*/*",
    "accept-language": "tr-TR,tr;q=0.9",
    "authorization": "SAPISIDHASH 1667340767_38d716c5c8afdeb3acffec97f15144726b19f1dd",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "pragma": "no-cache",
    "sec-ch-ua": "\"Chromium\";v=\"106\", \"Google Chrome\";v=\"106\", \"Not;A=Brand\";v=\"99\"",
    "sec-ch-ua-arch": "\"x86\"",
    "sec-ch-ua-bitness": "\"64\"",
    "sec-ch-ua-full-version": "\"106.0.5249.121\"",
    "sec-ch-ua-full-version-list": "\"Chromium\";v=\"106.0.5249.121\", \"Google Chrome\";v=\"106.0.5249.121\", \"Not;A=Brand\";v=\"99.0.0.0\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-model": "",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-ch-ua-platform-version": "\"14.0.0\"",
    "sec-ch-ua-wow64": "?0",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "same-origin",
    "sec-fetch-site": "same-origin",
    "x-goog-authuser": "0",
    "x-goog-visitor-id": "CgtmS2hGUEdIQlZxNCjltoabBg%3D%3D",
    "x-origin": "https://www.youtube.com",
    "x-youtube-bootstrap-logged-in": "true",
    "x-youtube-client-name": "1",
    "x-youtube-client-version": "2.20221026.05.00",
    "cookie": "YSC=QTqLZXcm_ho; VISITOR_INFO1_LIVE=fKhFPGHBVq4; SID=QQiA6WqjYah0MkDyIx2SqzCO7_f0Vfa3nRKUywZlJ9x-tQ51b-A-n0Nh4c2LNXAiaTxV_Q.; __Secure-1PSID=QQiA6WqjYah0MkDyIx2SqzCO7_f0Vfa3nRKUywZlJ9x-tQ51XKEO98TzhoCcAOO77tO1_Q.; __Secure-3PSID=QQiA6WqjYah0MkDyIx2SqzCO7_f0Vfa3nRKUywZlJ9x-tQ51gG4UlvUFBDckfaRhQawdpg.; HSID=A1-gvnVTk3lnhjxNy; SSID=AL3cKBnuH9pRKQg7R; APISID=X0bJ3qDub7EamFhe/AhpV7MSKk0UX-4jYp; SAPISID=KIkqaYfls7yO9Z_d/ACrkZvMo1mAFhpe0I; __Secure-1PAPISID=KIkqaYfls7yO9Z_d/ACrkZvMo1mAFhpe0I; __Secure-3PAPISID=KIkqaYfls7yO9Z_d/ACrkZvMo1mAFhpe0I; LOGIN_INFO=AFmmF2swRgIhAN9QY0NVKxCjUXE0wXOnKx9N9P3DfFxEbZ1Zg-WjDFhrAiEApa-aJPQKhre43A1eQK4XYsYMSM0u-fxF3V5Q-PhcBDg:QUQ3MjNmem9CSG5jT1BhTDVzanNncGhMcGtEUUM5M1hVSU9zWHJYRHR2RTZZVzVQZXFLaExuUmlrcmFUU1dMa2dLZDY4RXpfZDhPUmZpWDlxRUw1WmlLempHRFFpOTY1bUt3SWFHN3kzZ3B0T25lOUNVd3gwSE5QbXRNQkNYLTZ5cTFmM3MzZzhnRTVSc2FYeXRrQUkwWDRYNnktQmUzQjBn; PREF=f4=4000000&tz=Europe.Istanbul&f6=40000000&f7=100; wide=0; SIDCC=AIKkIs0o_vzKQ2nSFzRMGX2mi32Hzgc2tEtYbp-8OCUgToa2g3HhUKJ2cMyMDU_Z19snlABMPA; __Secure-1PSIDCC=AIKkIs0ndOtRDOo4eyiIgKIoeAheSgMpDgcbtFvKFzmm7AdLlxknJ7hsKqc6oOYxzIyTR2fD3iw; __Secure-3PSIDCC=AIKkIs1W-jbRyYX3rebpYhEwrZNQD5ALuY9K4DqVuD6YtzUPGs3hjpxvRHVTGhv4quh564gDTcM",
    "Referer": "https://www.youtube.com/live_chat?continuation=0ofMyAN6Gl5DaWtxSndvWVZVTlhUbkV6TVUwdGNUaEdkMlZ5UVhWbmJUZExkWFZCRWd0cFkwRllObk55UkVKaVNSb1Q2cWpkdVFFTkNndHBZMEZZTm5OeVJFSmlTU0FCTUFBJTNEMAGCAQIIBIgBAaABgdfA5oGO-wKoAQCyAQA%253D",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": "{\"context\":{\"client\":{\"hl\":\"tr\",\"gl\":\"TR\",\"remoteHost\":\"88.238.206.43\",\"deviceMake\":\"\",\"deviceModel\":\"\",\"visitorData\":\"CgtmS2hGUEdIQlZxNCjltoabBg%3D%3D\",\"userAgent\":\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36,gzip(gfe)\",\"clientName\":\"WEB\",\"clientVersion\":\"2.20221026.05.00\",\"osName\":\"Windows\",\"osVersion\":\"10.0\",\"originalUrl\":\"https://www.youtube.com/live_chat?continuation=0ofMyAN6Gl5DaWtxSndvWVZVTlhUbkV6TVUwdGNUaEdkMlZ5UVhWbmJUZExkWFZCRWd0cFkwRllObk55UkVKaVNSb1Q2cWpkdVFFTkNndHBZMEZZTm5OeVJFSmlTU0FCTUFBJTNEMAGCAQIIBIgBAaABgdfA5oGO-wKoAQCyAQA%253D\",\"screenPixelDensity\":2,\"platform\":\"DESKTOP\",\"clientFormFactor\":\"UNKNOWN_FORM_FACTOR\",\"configInfo\":{\"appInstallData\":\"COW2hpsGEOK5rgUQsoj-EhCf0K4FELjcrgUQuIuuBRDUg64FEIaR_hIQstauBRCfkP4SEJnGrgUQuNSuBRDA3K4FENi-rQUQkfj8Eg%3D%3D\"},\"screenDensityFloat\":1.5,\"userInterfaceTheme\":\"USER_INTERFACE_THEME_DARK\",\"timeZone\":\"Europe/Istanbul\",\"browserName\":\"Chrome\",\"browserVersion\":\"106.0.0.0\",\"acceptHeader\":\"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\",\"deviceExperimentId\":\"CgtFSWJfREVzUUZIYxDltoabBg%3D%3D\",\"screenWidthPoints\":897,\"screenHeightPoints\":558,\"utcOffsetMinutes\":180,\"connectionType\":\"CONN_CELLULAR_4G\",\"memoryTotalKbytes\":\"8000000\",\"mainAppWebInfo\":{\"graftUrl\":\"https://www.youtube.com/live_chat?continuation=0ofMyAN6Gl5DaWtxSndvWVZVTlhUbkV6TVUwdGNUaEdkMlZ5UVhWbmJUZExkWFZCRWd0cFkwRllObk55UkVKaVNSb1Q2cWpkdVFFTkNndHBZMEZZTm5OeVJFSmlTU0FCTUFBJTNEMAGCAQIIBIgBAaABgdfA5oGO-wKoAQCyAQA%253D\",\"webDisplayMode\":\"WEB_DISPLAY_MODE_BROWSER\",\"isWebNativeShareAvailable\":true}},\"user\":{\"lockedSafetyMode\":false},\"request\":{\"useSsl\":true,\"internalExperimentFlags\":[],\"consistencyTokenJars\":[]},\"clickTracking\":{\"clickTrackingParams\":\"CBMQ8FsiEwjPibDrgY77AhVyKeAKHa42Al0=\"},\"adSignalsInfo\":{\"params\":[{\"key\":\"dt\",\"value\":\"1667340760066\"},{\"key\":\"flash\",\"value\":\"0\"},{\"key\":\"frm\",\"value\":\"1\"},{\"key\":\"u_tz\",\"value\":\"180\"},{\"key\":\"u_his\",\"value\":\"3\"},{\"key\":\"u_h\",\"value\":\"1440\"},{\"key\":\"u_w\",\"value\":\"2560\"},{\"key\":\"u_ah\",\"value\":\"1392\"},{\"key\":\"u_aw\",\"value\":\"2560\"},{\"key\":\"u_cd\",\"value\":\"24\"},{\"key\":\"bc\",\"value\":\"31\"},{\"key\":\"bih\",\"value\":\"859\"},{\"key\":\"biw\",\"value\":\"947\"},{\"key\":\"brdim\",\"value\":\"0,0,0,0,2560,0,2560,1392,897,558\"},{\"key\":\"vis\",\"value\":\"1\"},{\"key\":\"wgl\",\"value\":\"true\"},{\"key\":\"ca_type\",\"value\":\"image\"}]}},\"params\":\"Q2lrcUp3b1lWVU5YVG5Fek1VMHRjVGhHZDJWeVFYVm5iVGRMZFhWQkVndHBZMEZZTm5OeVJFSmlTUkFCR0FRJTNE\",\"clientMessageId\":\"CJTqs-uBjvsCFXIp4AodrjYCXQ0\",\"richMessage\":{\"textSegments\":[{\"text\":\"hiii\"}]}}",
  "method": "POST"
});