name: Build and Deploy

on:
  workflow_dispatch:
  pull_request:
  # push:
  #   branches:
  #     - master

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  OWNER: ${{ secrets.OWNER }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  REDIS_USER: ${{ secrets.REDIS_USER }}
  REDIS_PWD: ${{ secrets.REDIS_PWD }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
  MGITHUB_OWNER: ${{ secrets.MGITHUB_OWNER }}
  MGITHUB_REPO: ${{ secrets.MGITHUB_REPO }}
  MGITHUB_WORKFLOW_TOKEN: ${{ secrets.MGITHUB_WORKFLOW_TOKEN }}
jobs:
  build:
    # Run on self-hosted if the private repo or ubuntu-latest if the public repo
    # See pull # 17442 in the private repo for context
    runs-on: [self-hosted, linux]
    timeout-minutes: 60
    steps:
      # Each of these ifs needs to be repeated at each step to make sure the required check still runs
      # Even if if doesn't do anything
      - name: Check out repo
        uses: actions/checkout@v3

      # - name: Setup node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 17.3.1
      - name: "Set environmental variables"
        run: |
          env

      - run: node --version
      - run: npm --version

      # - name: Install dependencies
      #   run: npm install

      # - name: Run deploy script
      #   run: |
      #     echo $OWNER
      #     echo "DISCORD_TOKEN=$DISCORD_TOKEN" >> $GITHUB_ENV
      #     echo "OWNER=$OWNER" >> $GITHUB_ENV
      #     echo "REDIS_URL=$REDIS_URL" >> $GITHUB_ENV
      #     echo "REDIS_USER=$REDIS_USER" >> $GITHUB_ENV
      #     echo "REDIS_PWD=$REDIS_PWD" >> $GITHUB_ENV
      #     echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> $GITHUB_ENV
      #     echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> $GITHUB_ENV
      #     echo "GOOGLE_REFRESH_TOKEN=$GOOGLE_REFRESH_TOKEN" >> $GITHUB_ENV
      #     echo "GITHUB_OWNER=$GITHUB_OWNER" >> $GITHUB_ENV
      #     echo "GITHUB_REPO=$GITHUB_REPO" >> $GITHUB_ENV
      #     echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV
      #     sh run.sh